run: # Configurations for a specific run
  random_seed: 1234 # Integer number of specifying random seed
  log_dir: None # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.
  time_log: True # Indicate whether to log the time for each step

audit: # Configurations for auditing
  privacy_game: privacy_loss_model # Indicate the privacy game from privacy_loss_model, avg_privacy_loss_training_algo, privacy_loss_sample
  attack_list: [rmia] # String for indicating the membership inference attack. We currently support population, reference.
  report_log: None # String that indicates the folder where we save the and auditing report.
  num_shadow_models: 5

# TODO: adapt or remove this
train: # Configuration for training
  num_target_model: 1 #Integer number for indicating how many target models we want to audit for the privacy game

# TODO: adapt or remove this
data: # Configuration for data
  data_dir: None # String about where to save the data.


LightningDataModule: 
  file_paths: 
    train: None
    validation: None
    test: None
    population: None
  representation: "MACCS"
  dataset_name: "ames"
  batch_size: 64
  num_workers: 8
  prefetch_factor: 8

LightningModule: 
  model_type: "MLP"
  hyperparameter_file_path: None
  target_model_path: None

moreno_result_folder:
  folder_path: /home/khcq385/results