run: # Configurations for a specific run
  random_seed: 1234 # Integer number of specifying random seed
  log_dir: ames_graph # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.
  time_log: True # Indicate whether to log the time for each step

audit: # Configurations for auditing
  privacy_game: privacy_loss_model # Indicate the privacy game from privacy_loss_model, avg_privacy_loss_training_algo, privacy_loss_sample
  attack_list: [rmia] # String for indicating the membership inference attack. We currently support population, reference.
  report_log: ames_graph # String that indicates the folder where we save the and auditing report.
  num_shadow_models: 5

# TODO: adapt or remove this
train: # Configuration for training
  num_target_model: 1 #Integer number for indicating how many target models we want to audit for the privacy game

# TODO: adapt or remove this
data: # Configuration for data
  data_dir: ./data # String about where to save the data.


LightningDataModule: 
  file_paths: 
    train: ../Local-chemical-space-finetuning/data/ames_random_train.csv
    validation: ../Local-chemical-space-finetuning/data/ames_random_validation.csv
    test: ../Local-chemical-space-finetuning/data/ames_random_test.csv
    population: ../Local-chemical-space-finetuning/data/ames_random_auxiliary.csv
  representation: "graph"
  dataset_name: "ames"
  batch_size: 64
  num_workers: 8
  prefetch_factor: 8

LightningModule: 
  model_type: "MPNN"
  hyperparameter_file_path: ./trained_models/results_ames_graph/optimized_hyperparameters.yaml
  target_model_path: trained_models/results_ames_graph/model_graph.ckpt